server:
  port: 8080
  servlet:
    context-path: /codelearning

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/CodeLearning}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        '[default_batch_fetch_size]': 10

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

jwt:
  signer-key: ${JWT_SIGNER_KEY}
  valid-duration: ${JWT_VALID_DURATION:180}
  refreshable-duration: ${JWT_REFRESHABLE_DURATION:360}

auth: 
  cookie:
    access-token:
      name: ${ACCESS_TOKEN_COOKIE_NAME:access_token}
      max-age: ${ACCESS_TOKEN_MAX_AGE:60}
      secure: ${ACCESS_TOKEN_SECURE:false}
      http-only: ${ACCESS_TOKEN_HTTP_ONLY:true}
      same-site: ${ACCESS_TOKEN_SAME_SITE:Lax}
      path: ${ACCESS_TOKEN_PATH:/}

    refresh-token:
      name: ${REFRESH_TOKEN_COOKIE_NAME:refresh_token}
      max-age: ${REFRESH_TOKEN_MAX_AGE:120}
      secure: ${REFRESH_TOKEN_SECURE:false}
      http-only: ${REFRESH_TOKEN_HTTP_ONLY:true}
      same-site: ${REFRESH_TOKEN_SAME_SITE:Lax}
      path: ${REFRESH_TOKEN_PATH:/codelearning/auth}




