-- -------------------------------------------------------------
-- SQL Migration: Add contest_rankings and contest_problem_attempts
-- Target DB: PostgreSQL (CodeLearning)
-- -------------------------------------------------------------

-- 1. Create contest_rankings Table
CREATE TABLE IF NOT EXISTS public.contest_rankings (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    contest_id bigint NOT NULL,
    user_id bigint NOT NULL,
    problems_solved integer NOT NULL DEFAULT 0,
    total_penalty integer NOT NULL DEFAULT 0,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    
    -- Primary & Unique constraints
    CONSTRAINT contest_rankings_pkey PRIMARY KEY (id),
    CONSTRAINT uq_contest_rankings_contest_user UNIQUE (contest_id, user_id),
    
    -- Value checks (note: constraint >= 0)
    CONSTRAINT chk_contest_rankings_problems_solved CHECK (problems_solved >= 0),
    CONSTRAINT chk_contest_rankings_total_penalty CHECK (total_penalty >= 0),
    
    -- Foreign keys with ON DELETE CASCADE
    CONSTRAINT fk_contest_rankings_contest FOREIGN KEY (contest_id) 
        REFERENCES public.contests(id) ON DELETE CASCADE,
    CONSTRAINT fk_contest_rankings_user FOREIGN KEY (user_id) 
        REFERENCES public.users(id) ON DELETE CASCADE
);

-- Owner configuration (matching the pattern in your db/init.sql)
ALTER TABLE public.contest_rankings OWNER TO postgres;


-- 2. Create contest_problem_attempts Table
CREATE TABLE IF NOT EXISTS public.contest_problem_attempts (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    contest_id bigint NOT NULL,
    user_id bigint NOT NULL,
    problem_id bigint NOT NULL,
    is_solved boolean NOT NULL DEFAULT false,
    solved_at_seconds integer,
    failed_attempts_count integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    
    -- Primary & Unique constraints
    CONSTRAINT contest_problem_attempts_pkey PRIMARY KEY (id),
    CONSTRAINT uq_contest_problem_attempts UNIQUE (contest_id, user_id, problem_id),
    
    -- Value checks (note: constraint >= 0)
    CONSTRAINT chk_contest_problem_attempts_solved_at CHECK (solved_at_seconds >= 0),
    CONSTRAINT chk_contest_problem_attempts_failed_attempts CHECK (failed_attempts_count >= 0),
    
    -- Foreign keys with ON DELETE CASCADE
    CONSTRAINT fk_contest_problem_attempts_contest FOREIGN KEY (contest_id) 
        REFERENCES public.contests(id) ON DELETE CASCADE,
    CONSTRAINT fk_contest_problem_attempts_user FOREIGN KEY (user_id) 
        REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT fk_contest_problem_attempts_problem FOREIGN KEY (problem_id) 
        REFERENCES public.online_judge_problems(id) ON DELETE CASCADE
);

-- Owner configuration (matching the pattern in your db/init.sql)
ALTER TABLE public.contest_problem_attempts OWNER TO postgres;

-- Indexes for performance (optional but highly recommended for fast ranking queries)
CREATE INDEX IF NOT EXISTS idx_contest_rankings_contest ON public.contest_rankings (contest_id);
CREATE INDEX IF NOT EXISTS idx_contest_problem_attempts_lookup ON public.contest_problem_attempts (contest_id, user_id);
