INSERT INTO courses (
    title,
    short_description,
    course_content,
    learning_outcomes,
    course_highlights,
    technologies_tools,
    prerequisites,
    target_audience,
    completion_benefits,
    price,
    thumbnail_url,
    estimated_duration_hours,
    status
)
VALUES
    (
        'Java Backend Development with Spring Boot',
        'Build production-ready REST APIs with Java, Spring Boot, Spring Security, JPA, PostgreSQL and JWT.',
        'This course covers Java backend development from project setup to building secure REST APIs. Learners will implement authentication, authorization, CRUD modules, database relationships, validation, exception handling, and API documentation.',
        'Understand Spring Boot project structure; Build RESTful APIs; Work with PostgreSQL using Spring Data JPA; Implement JWT authentication and role-based authorization; Handle validation and global exceptions.',
        'Real-world backend architecture; JWT authentication; Role-based access control; PostgreSQL relational database; Clean layered architecture.',
        'Java 21, Spring Boot, Spring Security, Spring Data JPA, PostgreSQL, Maven, Lombok, MapStruct',
        'Basic Java syntax, OOP concepts, basic SQL knowledge.',
        'Students who want to become backend developers; Java learners preparing for internship or fresher backend positions.',
        'After completing this course, learners can build and structure a real backend API project suitable for portfolio and CV.',
        499000.00,
        'https://example.com/thumbnails/java-spring-boot-backend.png',
        45,
        'ACTIVE'
    ),
    (
        'Data Structures and Algorithms for Coding Interviews',
        'Master essential data structures and algorithms through coding problems and online judge practice.',
        'This course teaches arrays, strings, linked lists, stacks, queues, trees, graphs, recursion, dynamic programming, greedy algorithms, and sorting/searching techniques with hands-on coding exercises.',
        'Solve common algorithmic problems; Analyze time and space complexity; Apply data structures correctly; Prepare for coding interviews and contests.',
        'Online judge practice; Problem-solving patterns; Interview-focused lessons; Step-by-step explanation of algorithms.',
        'Java, Online Judge, Big O Notation, Data Structures, Algorithms',
        'Basic programming knowledge in Java or another language.',
        'Students preparing for coding interviews, programming contests, or improving problem-solving skills.',
        'Learners will be able to solve medium-level coding problems and understand common algorithm patterns.',
        399000.00,
        'https://example.com/thumbnails/dsa-coding-interview.png',
        60,
        'ACTIVE'
    ),
    (
        'Fullstack Web Development with React and Spring Boot',
        'Create a complete fullstack web application using React, Spring Boot, REST API and PostgreSQL.',
        'This course guides learners through building a fullstack application from frontend UI to backend API. It includes React components, API integration, authentication flow, database design, and deployment preparation.',
        'Build React frontend pages; Connect frontend to Spring Boot APIs; Implement login and protected routes; Design database-backed fullstack features.',
        'Frontend-backend integration; Real project workflow; Authentication with JWT cookies; REST API consumption; Clean UI structure.',
        'React, TypeScript, Spring Boot, PostgreSQL, REST API, JWT',
        'Basic HTML, CSS, JavaScript and basic Java knowledge.',
        'Learners who want to build complete web applications and portfolio projects.',
        'After completing this course, learners can build a complete fullstack project and explain the system architecture in interviews.',
        699000.00,
        'https://example.com/thumbnails/fullstack-react-springboot.png',
        75,
        'ACTIVE'
    ),
    (
        'SQL and PostgreSQL for Backend Developers',
        'Learn relational database design, SQL queries, indexing, constraints and PostgreSQL best practices.',
        'This course focuses on practical SQL and PostgreSQL usage for backend developers. It covers database modeling, normalization, joins, indexes, constraints, transactions, and query optimization basics.',
        'Design relational schemas; Write SQL queries with joins and aggregations; Use constraints and indexes properly; Understand transactions and database consistency.',
        'Database design practice; PostgreSQL-specific features; Index and constraint usage; Backend-oriented SQL examples.',
        'PostgreSQL, SQL, ERD, Indexes, Constraints, Transactions',
        'Basic programming knowledge. No advanced database experience required.',
        'Backend beginners who want to understand databases deeply and design better schemas.',
        'Learners will be able to design and implement relational databases for real backend projects.',
        299000.00,
        'https://example.com/thumbnails/postgresql-backend.png',
        35,
        'ACTIVE'
    ),
    (
        'Docker and Deployment for Spring Boot Applications',
        'Package, containerize and deploy Spring Boot applications with Docker, PostgreSQL and Redis.',
        'This course teaches how to prepare a Spring Boot application for deployment. Learners will use Docker, Docker Compose, environment variables, PostgreSQL, Redis, and basic production configuration.',
        'Write Dockerfiles for Spring Boot; Configure Docker Compose; Use environment variables safely; Run PostgreSQL and Redis containers; Prepare backend apps for deployment.',
        'Dockerized backend setup; PostgreSQL and Redis containers; Environment-based configuration; Deployment-ready project structure.',
        'Docker, Docker Compose, Spring Boot, PostgreSQL, Redis, Environment Variables',
        'Basic Spring Boot knowledge and command-line usage.',
        'Backend developers who want to deploy real applications and understand container-based workflows.',
        'Learners can run their backend project consistently across local and deployment environments.',
        349000.00,
        'https://example.com/thumbnails/docker-springboot-deployment.png',
        30,
        'ACTIVE'
    );